### PR TITLE
Entropy fixes

### LINKED ISSUE #256: Entropy mobs shouldn't affect floor of subatomic dimension
The entropy mob should not affect the floor of the subatomic dimension. As far as I'm concerned, it is ok if the entropy mob does not spawn in the subatomic dimension at all

The entropy mob checks if a block is "dragon immune". In that case, the mob leaves the block unaffected. Like this, bed rock is unaffected. The subatomic-floor-block should be checked in the same way >> This is done through a vanilla tag that you have to  extend (replace=false)

### LINKED ISSUE #310: Entropy creeper moving Bohr building plate results in gamecrash
When an entropy creeper moves the Bohr building plate, the game moves the plate, then after some time crashes.

Afterwards the world may or may not be corrupted.

### LINKED ISSUE #358: Entropy creeper makes quantum fields not decay
When an entropy creeper explodes next to a quantum field cloud, every quantum field that is not connected to a the master block will never decay

#RemoveEntropyCreepersFromSubatomicDimension

### PR DESCRIPTION
**Pull request by pixar02**
fixes  #256, fixes #310 ,fixes   #358 
Added custom tag: ENTROPY_IMMUNE
Changed amount of entropy creepers spawning and there Biome selection.
Was ALL BIOMES (even custom ones), now only in all the Overworld and Nether ones.

### CODE REVIEW

**Comment by JoeyDP** [comment]
We could also restrict the blocks an entropy creeper can move further. For example all unbreakable blocks (see here https://github.com/ScicraftLearn/MineLabs/issues/256#issuecomment-1217551200) and all blocks that have block entities (chests, shulkers, craftings stations etc.). This should significantly reduce the number of bugs and crashes. Maybe also block pistons and piston arms for obvious reasons. Would this be feasible to implement?

**Comment by pixar02** [comment]
Yes, it's do-able. Just add blocks/entities to the list and done.
You could check for hardness and other stuff, but I don't know where that specific code came from and won't touch it.
So just adding a whitelist/blacklist (tag file) is the easiest/best solution in my opinion.

**Comment by thdaele** [comment]
It is a method in the abstract block class, it is used for calculating how long a player should do over mining a block. Also doesn't really matter where it comes from, that method shouldn't be edited. What Joey probably means is that you can do the same check of block hardness inside the code of entropy creeper where you check if a block should be moved by the entropy creeper. If block hardness is -1 than you don't consider the block for getting moved by entropy creeper.

**Comment by pixar02** [comment]
I know what he meant., I know adding a check for Hardness is not difficult.
But I meant the entropy code for getting all the Blocks and Entities.
**I ain't touching it.** 
It uses at least half alphabet in a single method without any comments on what is actually going on.

**Comment by JoeyDP** [comment]
I think you mean the decompiled code for fetching all the blocks. I wouldn't edit that either, but I did include a call to this function where new functionality can easily be added: https://github.com/ScicraftLearn/MineLabs/blob/ced76db97f2e1cae6f5a1936a5bcbf5f66459ad8/src/main/java/be/uantwerpen/minelabs/entity/EntropyCreeperEntity.java#L271

For now the listing is also good and we can add new stuff when @smtdm decides to break things again.

**Review by JoeyDP — APPROVED** [review]

**Pull request merged**
