### PR TITLE
Gamerules for quantum clouds

### PR DESCRIPTION
**Pull request by RandyParedis**
Ignore the fact that there are two commits - been a while since I did PRs :D

### CODE REVIEW

**Comment by pixar02** [comment]
> Ignore the fact that there are two commits - been a while since I did PRs :D

no files changed ??

**Comment by RandyParedis** [comment]
I... what?

**Comment by RandyParedis** [comment]
My commits clearly have changes, so I am soo confused rn lol

**Comment by RandyParedis** [comment]
Fixed it!

**Review by JoeyDP — APPROVED** [review]

**Pull request merged**
