### PR TITLE
Bohr fixes

### PR DESCRIPTION
**Pull request by JoeyDP**
Should be useable in structure block now (without option copy entities)

### CODE REVIEW

**Review by IneMEGAmaxi — APPROVED** [review]

**Comment by pixar02** [comment]
After "placing" the structure and right clicking the plate it just dissapears. (new structure made)

**Review by pixar02 — CHANGES_REQUESTED** [review]
After "placing" the structure and right clicking the plate it just dissapears. (new structure made)

**Comment by JoeyDP** [comment]
Changed to a version where you do need to copy entities. I also forgot to re-add a call to `updateCountsFromContents` which caused glitches in the last version..

**Review by pixar02 — APPROVED** [review]
Seems to work now.
Structure's need to have INCLUDE ENTITIES set to TRUE (ON). or it won't clear the bohr plate when loading a structure.

**Pull request merged**
