### PR TITLE
Entropy creeper update

### PR DESCRIPTION
**Pull request by JoeyDP**

### CODE REVIEW

**Comment by JoeyDP** [comment]
@smtdm do you have an estimate on when you could review this?

**Comment by pixar02** [comment]
Could we make an `EntropyExplosion` that does the actual logic. (Instead of forcing everything into the `EntropyCreeper`) 
It makes it easier to make "Entropy TNT"
-> Block spawns 'entropy tnt entity'
-> Entity does the actual call to the explosion.

**Comment by JoeyDP** [comment]
Certainly an option when we want to make Entropy TNT. I considered this in the initial design, but we hadn't made any entities yet back then so it seemed like the more difficult option. Would also use scheduled ticks instead of manually counting down probably.

**Review by smtdm — APPROVED** [review]
Works

**Pull request merged**
