### PR TITLE
Bohr plate rework first sprint

### LINKED ISSUE #498: Bohr plate: new block model

### LINKED ISSUE #499: Bohr plate: render info as boss bars
contains 3 bars:
protons (red), electrons (yellow) and neutrons (blue)
depending on the largest value the scaling is: 10 (discrete), 40 (discrete) and 150 (continuous mode)
depending on the problem if the entity is instable: electron or neutron bar glows red

left to the bars the element symbol is rendered with atom number, mass number and charge.
on top of the bars its value should also be rendered

### LINKED ISSUE #501: Bohr plate: create entity
inserting elements in the bohr plate  should be done by throwing/right clicking on the entity above it

this means the player interactions are as follows (regardless of content of their hand):
- left click on bohr plate = drop contents individually // destroy
- right click on bohr plate = drop atom if possible
- right click/ throw in/at atom = if electron/proton/neutron or antiparticle in hand: add to the entity

### LINKED ISSUE #514: Trigger rendering of bohr blueprint HUD when nearby
In event callback instead of using HitResult, query the entities near the player and render the hud of the nearest bohr blueprint within 8 blocks.

Note: Depends on the entity of the bohr blueprint (not blockentity).

### LINKED ISSUE #515: Bohr plate: Transition to Entity over BlockEntity
To construct the collision box of the atom above the bohr building plate we need to go beyond one block. This should be possible with an entity rather than a block entity.

Look into whether combination of entity, block and block entity is needed or a subset suffices. For example item frames are of AbstractDecorationEntity, but this also means they are destroyed when hit once etc., whereas we want an entity coupled with the block.

### LINKED ISSUE #517: Make atom particles throwable
All particles of an atom should be throwable to insert them into the bohr plate:

- Electron
- Proton
- Neutron
- Positron
- Anti-proton
- Anti-neutron

### LINKED ISSUE #518: Networking code rewrite crashes datagen
In the bohr_plate branch: usage of client only code in the server makes the runDatagen crash. This is caused by moving networking code.

### LINKED ISSUE #524: Update outline shape of bohr plate
VoxelShape.union of three parts.

### PR DESCRIPTION
**Pull request by JoeyDP**
- Closes #498
- Closes #515 
- Closes #517 
- Closes #518 
- Closes #501 
- Closes #514 
- Closes #524 
- Closes #499

### CODE REVIEW

**Comment by JoeyDP** [comment]
Closes:
- #498
- #515 
-  #517 
-  #518 
-  #501 
-  #514 
-  #524

**Comment by JoeyDP** [comment]
- Closes #498
- Closes #515 
- Closes #517 
- Closes #518 
- Closes #501 
- Closes #514 
- Closes #524

**Review by pixar02 — APPROVED** [review]
Code looks good.
Let's hope the Entity doesn't break things.... "/kill"

**Review by BertJorissen — APPROVED** [review]
looks good

**Pull request merged**
