### PR TITLE
Added recipes for lasertools and erlenmeyer

### LINKED ISSUE #603: Recipe: Erlenmeyer
afbeelding

### LINKED ISSUE #605: Recipe: lasertools
Add recipes for the lasertools. The Erlenmeyer is an erlenmeyer with Helium

Iron Lasertool
afbeelding

Gold lasertool
afbeelding

Diamond lasertool
afbeelding

### LINKED ISSUE #606: Crafting atoms takes a long time
https://docs.google.com/spreadsheets/d/1o6fBvC-Rwgv7CjSbvvpErOgW7ghoS2OsyKD4Lj1LSrM/edit?usp=sharing

(browser closed and the whole issue with possible fixes is lost befor i could save)

### PR DESCRIPTION
**Pull request by pixar02**
fixes #605 
fixes #603

### CODE REVIEW

**Comment by smtdm** [comment]
is it possible to make the recipe for the lasertool return an empty erlenmeyer?

**Comment by smtdm** [comment]
When you click in the recipe book to craft one or more lasertools, the erlenmeyer with helium is not added in the grid.
afbeelding

**Comment by pixar02** [comment]
> is it possible to make the recipe for the lasertool return an empty erlenmeyer?

Is there a recipe in vanilla that does that?

**Comment by JoeyDP** [comment]
This also means we can't have erlenmeyers stacking anymore, which could actually be a good thing with how the LCT currently works. What do you think @smtdm worth it?

**Comment by pixar02** [comment]
> This also means we can't have erlenmeyers stacking anymore, which could actually be a good thing with how the LCT currently works. What do you think @smtdm worth it?

They are still stackable.

**Comment by JoeyDP** [comment]
Wait what haha? Then where does the empty erlenmeyer go?

**Comment by pixar02** [comment]
> Wait what haha? Then where does the empty erlenmeyer go?

Where there is space. So either in the slot of the crafting table (when there is only 1 helium used) or any slot in the players inventory if there is room. Otherwise it would just drop on the ground.

**Review by smtdm — APPROVED** [review]

**Pull request merged**
