### PR TITLE
Mologram

### PR DESCRIPTION
**Pull request by IneMEGAmaxi**
Do the thing, @smtdm!

Maybe we want some clean up of MoleculeModel and MologramBeamModel and tweaking of the height of the beams/ molecule.
But other than that it seems that the mologram is ready?

texture animations will be an enhancement later

### CODE REVIEW

**Comment by pixar02** [comment]
Before someone says "ERLENMEYER_HNO3" and "ERLENMEYER_H2O" don't work. 
Fluid Erlenmeyers are still being worked on. When implementing them they only need to `implement MoleculeItem`.
Using a basic version (of such an implementation) results in the folowing (HNO3 is used):

**Review by smtdm — COMMENTED** [review]
Issue #429 
Issue #430
Issue #431
(Issue #432 enhancement)

**Comment by pixar02** [comment]
Fixes #430, fixes#431 (just need correct strings for advanced ones), fixes #432 (max when item present, 0 when empty)

**Review by smtdm — APPROVED** [review]
Pretty much perfect

**Pull request merged**
