### PR TITLE
Bohr/fixes

### LINKED ISSUE #643: Bohr plate: set light level to 0
The bohr plate does not need to emit light anymore. Remove from block settings.

### LINKED ISSUE #645: bohr plate: increase max capacity
Current max protons, neutrons and electrons is set to that of Oganesson (p:118 n: 176). To allow the player to experiment with configurations around this atom I suggest the following capacities:

- protons: 118
- neutrons: 180
- electrons: 118 + 8

We still limit the protons which allows us to render the atom symbol at all times. Otherwise we need to make edge cases for elements > 118. The neutron count is rounded to 180 and we have stability info from the stable diagonal chart. Electrons are capped at their max divergence from protons which will be implemented this sprint.

### LINKED ISSUE #653: Bohr plate: additionally check intersection of thrown particle and bohr entity upon creation
**Is your feature request related to a problem? Please describe.**
Thrown particles are not added to the bohr plate if they are thrown from within the entity.

**Describe the solution you'd like**
When a particle is created (thrown) do a one time check to see whether its hitbox collides with a bohr blueprint entity. If so call `SubatomicParticleEntity::onEntityHit`.

**Describe alternatives you've considered**
Doing this in the tick function, but this solution is more efficient if it works.

### PR DESCRIPTION
**Pull request by pixar02**
- fixes #653
- fixes #645
- fixes #643

### CODE REVIEW

**Review by JoeyDP — APPROVED** [review]

**Comment by JoeyDP** [comment]
I moved the collision check to the entity so it works independent of how they are spawned

**Comment by pixar02** [comment]
> I moved the collision check to the entity so it works independent of how they are spawned

Looks good. Just don't remove the closest Bohr check. (otherwise: place 2 bohr next to each other and both get the item, when standing between them)

**Comment by JoeyDP** [comment]
If there are multiple collisions the particle only handles one and then the isRemoved check breaks the loop. In your test I assume the bounding box collides with both and then which one it goes to depends on their order as returned by the world object. This seems fine by me as it actually collides with both and if a player chooses to create this scenario it's on them 🙈

**Comment by JoeyDP** [comment]
Would a check for the closest one be more intuitive?

**Comment by JoeyDP** [comment]
> I believe so. It makes sense, even if the distance is less then a few pixels.

Added and tested in game. Since you are the author of this PR and can't review, feel free to merge when you approve.

**Pull request merged**
