### PR TITLE
Coulomb move

### PR DESCRIPTION
**Pull request by JoeyDP**
Changes inheritance to higher up the chain and implement movement ourselves in tick function with `move` function.

### CODE REVIEW

**Comment by JoeyDP** [comment]
Still has sever client desync issues, likely due to crash when loading data (#784)

**Comment by JoeyDP** [comment]
Can this be merged into the coulomb development branch?

**Comment by pixar02** [comment]
Could this be updated ? 
Now that the "base" branch is "stable" (enough), I'm intressted in other possibilities.

**Comment by JoeyDP** [comment]
> Could this be updated ? Now that the "base" branch is "stable" (enough), I'm intressted in other possibilities.

I tried to merge it for about an hour and had to call it. Better to redo the work than relying on git to figure out where the code needs to go at this point.

**Pull request closed without merging**
